from enum import StrEnum


class Severidad(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class AuthErrorCode(StrEnum):
    UNKNOWN = "AUTH_UNKNOWN"
    INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    INVALID_TOKEN = "AUTH_TOKEN_INVALID"
    INVALID_CSRF = "AUTH_CSRF_INVALID"
    INVALID_ORIGIN = "AUTH_ORIGIN_INVALID"
    PASSWORD_INVALID = "AUTH_PASSWORD_INVALID"
    PASSWORD_CHANGE_REQUIRED = "AUTH_PASSWORD_CHANGE_REQUIRED"
    FORBIDDEN = "AUTH_FORBIDDEN"
    USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    USER_EXISTS = "AUTH_USER_EXISTS"
    ADMIN_EXISTS = "AUTH_ADMIN_EXISTS"
    LAST_ADMIN_REQUIRED = "AUTH_LAST_ADMIN_REQUIRED"
    INPUT_INVALID = "AUTH_INPUT_INVALID"
    REFRESH_CONFLICT = "AUTH_REFRESH_CONFLICT"
    CONFIG_INVALID = "AUTH_CONFIG_INVALID"
    PASSKEY_CHALLENGE_INVALID = "AUTH_PASSKEY_CHALLENGE_INVALID"
    PASSKEY_REGISTRATION_INVALID = "AUTH_PASSKEY_REGISTRATION_INVALID"
    PASSKEY_AUTHENTICATION_INVALID = "AUTH_PASSKEY_AUTHENTICATION_INVALID"
    PASSKEY_EXISTS = "AUTH_PASSKEY_EXISTS"
    PASSKEY_NOT_FOUND = "AUTH_PASSKEY_NOT_FOUND"
    PASSKEY_LIMIT_REACHED = "AUTH_PASSKEY_LIMIT_REACHED"
    PASSKEY_NAME_INVALID = "AUTH_PASSKEY_NAME_INVALID"
    GOOGLE_CHALLENGE_INVALID = "AUTH_GOOGLE_CHALLENGE_INVALID"
    GOOGLE_CREDENTIAL_INVALID = "AUTH_GOOGLE_CREDENTIAL_INVALID"
    GOOGLE_IDENTITY_CONFLICT = "AUTH_GOOGLE_IDENTITY_CONFLICT"
    GOOGLE_IDENTITY_NOT_FOUND = "AUTH_GOOGLE_IDENTITY_NOT_FOUND"
    GOOGLE_SERVICE_UNAVAILABLE = "AUTH_GOOGLE_SERVICE_UNAVAILABLE"


CodigoError = AuthErrorCode

UNKNOWN_ERROR_DETAIL = "An unexpected authentication error occurred."

_ERROR_CODES = {
    AuthErrorCode.UNKNOWN,
    AuthErrorCode.CONFIG_INVALID,
    AuthErrorCode.GOOGLE_SERVICE_UNAVAILABLE,
}


def severidad_default(code: AuthErrorCode) -> Severidad:
    if code in _ERROR_CODES:
        return Severidad.ERROR
    return Severidad.WARNING
