from collections.abc import Sequence
from contextlib import AbstractAsyncContextManager
from datetime import datetime
from typing import Protocol
from uuid import UUID

from epok_auth.models import RefreshSession, SecurityEvent, UserAccount


class StoreConflictError(Exception):
    """Persistence-level uniqueness or transactional conflict."""


class AuthTransaction(Protocol):
    async def acquire_admin_invariant_lock(self) -> None: ...
    async def count_users_with_role(self, role: str, *, active_only: bool) -> int: ...
    async def get_user_by_email(
        self, email: str, *, for_update: bool = False
    ) -> UserAccount | None: ...
    async def get_user_by_id(
        self, user_id: UUID, *, for_update: bool = False
    ) -> UserAccount | None: ...
    async def list_users(self, *, limit: int, offset: int) -> Sequence[UserAccount]: ...
    async def insert_user(self, user: UserAccount) -> None: ...
    async def update_user(self, user: UserAccount) -> None: ...
    async def get_session_by_token_hash(
        self, token_hash: str, *, for_update: bool = False
    ) -> RefreshSession | None: ...
    async def get_session_by_id(
        self, session_id: UUID, *, for_update: bool = False
    ) -> RefreshSession | None: ...
    async def insert_session(self, session: RefreshSession) -> None: ...
    async def update_session(self, session: RefreshSession) -> None: ...
    async def revoke_family(self, family_id: UUID, *, revoked_at: datetime) -> int: ...
    async def revoke_user_sessions(self, user_id: UUID, *, revoked_at: datetime) -> int: ...
    async def add_security_event(self, event: SecurityEvent) -> None: ...


class AuthStore(Protocol):
    def transaction(self) -> AbstractAsyncContextManager[AuthTransaction]: ...
